### ISSUE TITLE
User grants

### ISSUE THREAD

**Issue by sobiso** [TarikHuber/rmw-shell#13]
Correct me if i am wrong. User grants are saved in 'user_grants' as array:
0: true
1: false
6: false

array index ( from grants.js file) and bool value

I think that is not best idea, what will be happen if we switch lines in this grants.js file
example 
from
  'create_company',
  'edit_company',
  'delete_company',

to
  'edit_company',
  'create_company',
  'delete_company',

**Comment by TarikHuber** [comment]
Hi @sobiso ,

Yes the grants are saved in an array. But they are just enumerables and should stay static. That array i just for the internal naming of the grants. The actual value (true or false) is saved on the Firebase realtime database for each user. 

So if you switch lines nothing will happen because we use the grants array just to list all possible arrays in the roles and user grants UI. 

Let me know if this helps and if there are more questions.

**Comment by sobiso** [comment]
So how you know that 0 (index in firebase) is ie. 'edit_company' ?

**Comment by TarikHuber** [comment]
@sobiso in firebase it is saved by 'edit_company' there are no indexes at all.

**Comment by sobiso** [comment]
Ok so maybe i have old version, because 
![image](https://user-images.githubusercontent.com/7464868/41215117-111d18fe-6d4f-11e8-9c4c-ae51330d8ab5.png)

**Comment by TarikHuber** [comment]
Ouuu you are right. There are some with indexes. Will check that ASAP. thx :smile:
![unbenannt](https://user-images.githubusercontent.com/11230962/41215208-805cda24-6d4f-11e8-8fde-2917b3977d7a.PNG)

**Comment by TarikHuber** [comment]
OK it seems to be a bug with the new main version. Will fix it ASAP. thx again @sobiso 😄
